export {default as Home} from './pages/Home'
export {default as Productlist} from './pages/Productlist'
export {default as Product} from './pages/Product'
export {default as Cart} from './pages/Cart'
export {default as Login} from './pages/Login'
export {default as Signup} from './pages/Signup'
export {default as Order} from './pages/Order'